@echo off
echo Creating custom extension artefacts...
call createMyExt.bat
echo Creating custom document artefacts...
call createRAR.bat
echo Creating UBL base and extension artefacts...
call createUBL.bat
echo Validating test instances...
cd val
call test.bat
cd ..

