echo RAR document...
echo ...checking...
java -jar ../saxon9he/saxon9he.jar -o:checkRAR.html -s:mod/MyRARequestResponse-Entities.gc -xsl:../Crane-checkgc4obdndr.xsl config-uri=../config-rar.xml base-config-uri=../config-ubl-2.1.xml base-gc-uri=UBL-Entities-2.1.gc "title-suffix=Demo RAR" "change-suffix=Demo"
if [ "$?" != "0" ]; then exit ; fi

echo ...building RARequest... 
java -jar ../saxon9he/saxon9he.jar -s:mod/MyRARequestResponse-Entities.gc -xsl:../Crane-gc2obdndr.xsl -o:junk.out config-uri=../config-rar.xml base-uri=UBL-Entities-2.1.gc base-config-uri=../config-ubl-2.1.xml base-gc-uri=UBL-Entities-2.1.gc
if [ "$?" != "0" ]; then exit ; fi

echo ...summarizing...
java -jar ../saxon9he/saxon9he.jar -o:summary/junk.out all-documents-base-name=RARDocuments -s:mod/MyRARequestResponse-Entities.gc -xsl:../Crane-gc2obdsummary.xsl config-uri=../config-rar.xml base-summary-uri=UBL-Invoice-2.1.html base-gc-uri=UBL-Entities-2.1.gc "title-prefix=Demo RAR" "copyright-text=Copyright &#169; example.com; Portions copyright &#169; OASIS Open"
if [ "$?" != "0" ]; then exit ; fi
