echo Creating custom extension artefacts...
sh createMyExt.sh
echo Creating custom document artefacts...
sh createRAR.sh
echo Creating UBL artefacts...
sh createUBL.sh
echo Validating test instances...
cd val
sh test.sh
cd ..
