call validatejson  ..\json-schema\maindoc\UBL-TransportationStatus-2.3.json ..\json\MyTransportationStatus.json
call validatejson  ..\json-schema\maindoc\UBL-BusinessCard-2.3.json ..\json\UBL-BusinessCard-2.2-Example.json
call validatejson  ..\json-schema\maindoc\UBL-CreditNote-2.3.json ..\json\UBL-CreditNote-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-CreditNote-2.3.json ..\json\UBL-CreditNote-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-DebitNote-2.3.json ..\json\UBL-DebitNote-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-DespatchAdvice-2.3.json ..\json\UBL-DespatchAdvice-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-DigitalAgreement-2.3.json ..\json\UBL-DigitalAgreement-2.2-Example-Multilateral.json
call validatejson  ..\json-schema\maindoc\UBL-DigitalAgreement-2.3.json ..\json\UBL-DigitalAgreement-2.2-Example.json
call validatejson  ..\json-schema\maindoc\UBL-DigitalCapability-2.3.json ..\json\UBL-DigitalCapability-2.2-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ExceptionCriteria-2.3.json ..\json\UBL-ExceptionCriteria-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ExceptionNotification-2.3.json ..\json\UBL-ExceptionNotification-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ExportCustomsDeclaration-2.3.json ..\json\UBL-ExportCustomsDeclaration-2.3-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ExpressionOfInterestRequest-2.3.json ..\json\UBL-ExpressionOfInterestRequest-2.2-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Forecast-2.3.json ..\json\UBL-Forecast-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ForecastRevision-2.3.json ..\json\UBL-ForecastRevision-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ForwardingInstructions-2.3.json ..\json\UBL-ForwardingInstructions-2.0-Example-International.json
call validatejson  ..\json-schema\maindoc\UBL-FreightInvoice-2.3.json ..\json\UBL-FreightInvoice-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-FulfilmentCancellation-2.3.json ..\json\UBL-FulfilmentCancellation-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-GoodsCertificate-2.3.json ..\json\UBL-GoodsCertificate-2.3-Example.json
call validatejson  ..\json-schema\maindoc\UBL-GoodsItemItinerary-2.3.json ..\json\UBL-GoodsItemItinerary-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-GoodsItemPassport-2.3.json ..\json\UBL-GoodsItemPassport-2.3-Example-Issued.json
call validatejson  ..\json-schema\maindoc\UBL-InstructionForReturns-2.3.json ..\json\UBL-InstructionForReturns-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-InventoryReport-2.3.json ..\json\UBL-InventoryReport-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Detached.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Enveloped.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Example-NS1.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Example-NS2.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Example-NS3.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Example-NS4.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.1-Example-Trivial.json
call validatejson  ..\json-schema\maindoc\UBL-Invoice-2.3.json ..\json\UBL-Invoice-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Order-2.3.json ..\json\UBL-Order-2.0-Example-International.json
call validatejson  ..\json-schema\maindoc\UBL-Order-2.3.json ..\json\UBL-Order-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Order-2.3.json ..\json\UBL-Order-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-OrderCancellation-2.3.json ..\json\UBL-OrderCancellation-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-OrderChange-2.3.json ..\json\UBL-OrderChange-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-OrderResponse-2.3.json ..\json\UBL-OrderResponse-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-OrderResponseSimple-2.3.json ..\json\UBL-OrderResponseSimple-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-OrderResponseSimple-2.3.json ..\json\UBL-OrderResponseSimple-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-PriorInformationNotice-2.3.json ..\json\UBL-PriorInformationNotice-2.2-Example-Embedded.json
call validatejson  ..\json-schema\maindoc\UBL-PriorInformationNotice-2.3.json ..\json\UBL-PriorInformationNotice-2.2-Example-External.json
call validatejson  ..\json-schema\maindoc\UBL-ProductActivity-2.3.json ..\json\UBL-ProductActivity-2.1-Example-1.json
call validatejson  ..\json-schema\maindoc\UBL-ProductActivity-2.3.json ..\json\UBL-ProductActivity-2.1-Example-2.json
call validatejson  ..\json-schema\maindoc\UBL-ProductActivity-2.3.json ..\json\UBL-ProductActivity-2.1-Example-3.json
call validatejson  ..\json-schema\maindoc\UBL-ProofOfReexportation-2.3.json ..\json\UBL-ProofOfReexportation-2.3-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ProofOfReexportationRequest-2.3.json ..\json\UBL-ProofOfReexportationRequest-2.3-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Quotation-2.3.json ..\json\UBL-Quotation-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Quotation-2.3.json ..\json\UBL-Quotation-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-ReceiptAdvice-2.3.json ..\json\UBL-ReceiptAdvice-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Reminder-2.3.json ..\json\UBL-Reminder-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-RemittanceAdvice-2.3.json ..\json\UBL-RemittanceAdvice-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-RequestForQuotation-2.3.json ..\json\UBL-RequestForQuotation-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-RequestForQuotation-2.3.json ..\json\UBL-RequestForQuotation-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-RetailEvent-2.3.json ..\json\UBL-RetailEvent-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-SelfBilledCreditNote-2.3.json ..\json\UBL-SelfBilledCreditNote-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Statement-2.3.json ..\json\UBL-Statement-2.0-Example.json
call validatejson  ..\json-schema\maindoc\UBL-StockAvailabilityReport-2.3.json ..\json\UBL-StockAvailabilityReport-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TradeItemLocationProfile-2.3.json ..\json\UBL-TradeItemLocationProfile-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportExecutionPlan-2.3.json ..\json\UBL-TransportExecutionPlan-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportExecutionPlanRequest-2.3.json ..\json\UBL-TransportExecutionPlanRequest-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportProgressStatus-2.3.json ..\json\UBL-TransportProgressStatus-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportProgressStatusRequest-2.3.json ..\json\UBL-TransportProgressStatusRequest-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportServiceDescription-2.3.json ..\json\UBL-TransportServiceDescription-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportServiceDescriptionRequest-2.3.json ..\json\UBL-TransportServiceDescriptionRequest-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportationStatus-2.3.json ..\json\UBL-TransportationStatus-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-TransportationStatusRequest-2.3.json ..\json\UBL-TransportationStatusRequest-2.1-Example.json
call validatejson  ..\json-schema\maindoc\UBL-Waybill-2.3.json ..\json\UBL-Waybill-2.0-Example-International.json
call validatejson  ..\json-schema\maindoc\UBL-WeightStatement-2.3.json ..\json\UBL-WeightStatement-2.2-Example.json
