UBLversion=2.4
sh validatejson.sh ../json-schema/maindoc/UBL-TransportationStatus-$UBLversion.json ../json/MyTransportationStatus.json
sh validatejson.sh ../json-schema/maindoc/UBL-BusinessCard-$UBLversion.json ../json/UBL-BusinessCard-2.2-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-CreditNote-$UBLversion.json ../json/UBL-CreditNote-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-CreditNote-$UBLversion.json ../json/UBL-CreditNote-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-DebitNote-$UBLversion.json ../json/UBL-DebitNote-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-DespatchAdvice-$UBLversion.json ../json/UBL-DespatchAdvice-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-DigitalAgreement-$UBLversion.json ../json/UBL-DigitalAgreement-2.2-Example-Multilateral.json
sh validatejson.sh ../json-schema/maindoc/UBL-DigitalAgreement-$UBLversion.json ../json/UBL-DigitalAgreement-2.2-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-DigitalCapability-$UBLversion.json ../json/UBL-DigitalCapability-2.2-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ExceptionCriteria-$UBLversion.json ../json/UBL-ExceptionCriteria-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ExceptionNotification-$UBLversion.json ../json/UBL-ExceptionNotification-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ExportCustomsDeclaration-$UBLversion.json ../json/UBL-ExportCustomsDeclaration-$UBLversion-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ExpressionOfInterestRequest-$UBLversion.json ../json/UBL-ExpressionOfInterestRequest-2.2-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Forecast-$UBLversion.json ../json/UBL-Forecast-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ForecastRevision-$UBLversion.json ../json/UBL-ForecastRevision-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ForwardingInstructions-$UBLversion.json ../json/UBL-ForwardingInstructions-2.0-Example-International.json
sh validatejson.sh ../json-schema/maindoc/UBL-FreightInvoice-$UBLversion.json ../json/UBL-FreightInvoice-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-FulfilmentCancellation-$UBLversion.json ../json/UBL-FulfilmentCancellation-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-GoodsCertificate-$UBLversion.json ../json/UBL-GoodsCertificate-$UBLversion-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-GoodsItemItinerary-$UBLversion.json ../json/UBL-GoodsItemItinerary-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-GoodsItemPassport-$UBLversion.json ../json/UBL-GoodsItemPassport-$UBLversion-Example-Issued.json
sh validatejson.sh ../json-schema/maindoc/UBL-InstructionForReturns-$UBLversion.json ../json/UBL-InstructionForReturns-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-InventoryReport-$UBLversion.json ../json/UBL-InventoryReport-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Detached.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Enveloped.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Example-NS1.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Example-NS2.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Example-NS3.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Example-NS4.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.1-Example-Trivial.json
sh validatejson.sh ../json-schema/maindoc/UBL-Invoice-$UBLversion.json ../json/UBL-Invoice-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Order-$UBLversion.json ../json/UBL-Order-2.0-Example-International.json
sh validatejson.sh ../json-schema/maindoc/UBL-Order-$UBLversion.json ../json/UBL-Order-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Order-$UBLversion.json ../json/UBL-Order-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-OrderCancellation-$UBLversion.json ../json/UBL-OrderCancellation-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-OrderChange-$UBLversion.json ../json/UBL-OrderChange-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-OrderResponse-$UBLversion.json ../json/UBL-OrderResponse-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-OrderResponseSimple-$UBLversion.json ../json/UBL-OrderResponseSimple-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-OrderResponseSimple-$UBLversion.json ../json/UBL-OrderResponseSimple-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-PriorInformationNotice-$UBLversion.json ../json/UBL-PriorInformationNotice-2.2-Example-Embedded.json
sh validatejson.sh ../json-schema/maindoc/UBL-PriorInformationNotice-$UBLversion.json ../json/UBL-PriorInformationNotice-2.2-Example-External.json
sh validatejson.sh ../json-schema/maindoc/UBL-ProductActivity-$UBLversion.json ../json/UBL-ProductActivity-2.1-Example-1.json
sh validatejson.sh ../json-schema/maindoc/UBL-ProductActivity-$UBLversion.json ../json/UBL-ProductActivity-2.1-Example-2.json
sh validatejson.sh ../json-schema/maindoc/UBL-ProductActivity-$UBLversion.json ../json/UBL-ProductActivity-2.1-Example-3.json
sh validatejson.sh ../json-schema/maindoc/UBL-ProofOfReexportation-$UBLversion.json ../json/UBL-ProofOfReexportation-$UBLversion-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ProofOfReexportationRequest-$UBLversion.json ../json/UBL-ProofOfReexportationRequest-$UBLversion-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Quotation-$UBLversion.json ../json/UBL-Quotation-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Quotation-$UBLversion.json ../json/UBL-Quotation-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-ReceiptAdvice-$UBLversion.json ../json/UBL-ReceiptAdvice-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Reminder-$UBLversion.json ../json/UBL-Reminder-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-RemittanceAdvice-$UBLversion.json ../json/UBL-RemittanceAdvice-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-RequestForQuotation-$UBLversion.json ../json/UBL-RequestForQuotation-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-RequestForQuotation-$UBLversion.json ../json/UBL-RequestForQuotation-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-RetailEvent-$UBLversion.json ../json/UBL-RetailEvent-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-SelfBilledCreditNote-$UBLversion.json ../json/UBL-SelfBilledCreditNote-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Statement-$UBLversion.json ../json/UBL-Statement-2.0-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-StockAvailabilityReport-$UBLversion.json ../json/UBL-StockAvailabilityReport-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TradeItemLocationProfile-$UBLversion.json ../json/UBL-TradeItemLocationProfile-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportExecutionPlan-$UBLversion.json ../json/UBL-TransportExecutionPlan-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportExecutionPlanRequest-$UBLversion.json ../json/UBL-TransportExecutionPlanRequest-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportProgressStatus-$UBLversion.json ../json/UBL-TransportProgressStatus-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportProgressStatusRequest-$UBLversion.json ../json/UBL-TransportProgressStatusRequest-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportServiceDescription-$UBLversion.json ../json/UBL-TransportServiceDescription-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportServiceDescriptionRequest-$UBLversion.json ../json/UBL-TransportServiceDescriptionRequest-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportationStatus-$UBLversion.json ../json/UBL-TransportationStatus-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-TransportationStatusRequest-$UBLversion.json ../json/UBL-TransportationStatusRequest-2.1-Example.json
sh validatejson.sh ../json-schema/maindoc/UBL-Waybill-$UBLversion.json ../json/UBL-Waybill-2.0-Example-International.json
sh validatejson.sh ../json-schema/maindoc/UBL-WeightStatement-$UBLversion.json ../json/UBL-WeightStatement-2.2-Example.json
