sh validatejson.sh ../json-schema-model/maindoc/UBL-BusinessCard-2.3.json ../json-model/UBL-BusinessCard-2.2-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-CommonTransportationReport-2.3.json ../json-model/UBL-CommonTransportationReport-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-CreditNote-2.3.json ../json-model/UBL-CreditNote-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-CreditNote-2.3.json ../json-model/UBL-CreditNote-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-DebitNote-2.3.json ../json-model/UBL-DebitNote-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-DespatchAdvice-2.3.json ../json-model/UBL-DespatchAdvice-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-DigitalAgreement-2.3.json ../json-model/UBL-DigitalAgreement-2.2-Example-Multilateral.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-DigitalAgreement-2.3.json ../json-model/UBL-DigitalAgreement-2.2-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-DigitalCapability-2.3.json ../json-model/UBL-DigitalCapability-2.2-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ExceptionCriteria-2.3.json ../json-model/UBL-ExceptionCriteria-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ExceptionNotification-2.3.json ../json-model/UBL-ExceptionNotification-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ExportCustomsDeclaration-2.3.json ../json-model/UBL-ExportCustomsDeclaration-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ExpressionOfInterestRequest-2.3.json ../json-model/UBL-ExpressionOfInterestRequest-2.2-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Forecast-2.3.json ../json-model/UBL-Forecast-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ForecastRevision-2.3.json ../json-model/UBL-ForecastRevision-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ForwardingInstructions-2.3.json ../json-model/UBL-ForwardingInstructions-2.0-Example-International.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-FreightInvoice-2.3.json ../json-model/UBL-FreightInvoice-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-FulfilmentCancellation-2.3.json ../json-model/UBL-FulfilmentCancellation-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-GoodsCertificate-2.3.json ../json-model/UBL-GoodsCertificate-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-GoodsItemItinerary-2.3.json ../json-model/UBL-GoodsItemItinerary-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-GoodsItemPassport-2.3.json ../json-model/UBL-GoodsItemPassport-2.3-Example-Issued.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-InstructionForReturns-2.3.json ../json-model/UBL-InstructionForReturns-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-InventoryReport-2.3.json ../json-model/UBL-InventoryReport-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Detached.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Example-NS1.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Example-NS2.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Example-NS3.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Example-NS4.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.1-Example-Trivial.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Invoice-2.3.json ../json-model/UBL-Invoice-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Manifest-2.3.json ../json-model/UBL-Manifest-2.3-Example-Reference-Only.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Manifest-2.3.json ../json-model/UBL-Manifest-2.3-Example-Shipment.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Order-2.3.json ../json-model/UBL-Order-2.0-Example-International.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Order-2.3.json ../json-model/UBL-Order-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Order-2.3.json ../json-model/UBL-Order-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-OrderCancellation-2.3.json ../json-model/UBL-OrderCancellation-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-OrderChange-2.3.json ../json-model/UBL-OrderChange-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-OrderResponse-2.3.json ../json-model/UBL-OrderResponse-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-OrderResponseSimple-2.3.json ../json-model/UBL-OrderResponseSimple-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-OrderResponseSimple-2.3.json ../json-model/UBL-OrderResponseSimple-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-PriorInformationNotice-2.3.json ../json-model/UBL-PriorInformationNotice-2.2-Example-Embedded.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-PriorInformationNotice-2.3.json ../json-model/UBL-PriorInformationNotice-2.2-Example-External.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProductActivity-2.3.json ../json-model/UBL-ProductActivity-2.1-Example-1.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProductActivity-2.3.json ../json-model/UBL-ProductActivity-2.1-Example-2.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProductActivity-2.3.json ../json-model/UBL-ProductActivity-2.1-Example-3.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProofOfReexportation-2.3.json ../json-model/UBL-ProofOfReexportation-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProofOfReexportationReminder-2.3.json ../json-model/UBL-ProofOfReexportationReminder-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ProofOfReexportationRequest-2.3.json ../json-model/UBL-ProofOfReexportationRequest-2.3-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Quotation-2.3.json ../json-model/UBL-Quotation-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Quotation-2.3.json ../json-model/UBL-Quotation-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-ReceiptAdvice-2.3.json ../json-model/UBL-ReceiptAdvice-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Reminder-2.3.json ../json-model/UBL-Reminder-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-RemittanceAdvice-2.3.json ../json-model/UBL-RemittanceAdvice-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-RequestForQuotation-2.3.json ../json-model/UBL-RequestForQuotation-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-RequestForQuotation-2.3.json ../json-model/UBL-RequestForQuotation-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-RetailEvent-2.3.json ../json-model/UBL-RetailEvent-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-SelfBilledCreditNote-2.3.json ../json-model/UBL-SelfBilledCreditNote-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Statement-2.3.json ../json-model/UBL-Statement-2.0-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-StockAvailabilityReport-2.3.json ../json-model/UBL-StockAvailabilityReport-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TradeItemLocationProfile-2.3.json ../json-model/UBL-TradeItemLocationProfile-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportExecutionPlan-2.3.json ../json-model/UBL-TransportExecutionPlan-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportExecutionPlanRequest-2.3.json ../json-model/UBL-TransportExecutionPlanRequest-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportProgressStatus-2.3.json ../json-model/UBL-TransportProgressStatus-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportProgressStatusRequest-2.3.json ../json-model/UBL-TransportProgressStatusRequest-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportServiceDescription-2.3.json ../json-model/UBL-TransportServiceDescription-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportServiceDescriptionRequest-2.3.json ../json-model/UBL-TransportServiceDescriptionRequest-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportationStatus-2.3.json ../json-model/UBL-TransportationStatus-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-TransportationStatusRequest-2.3.json ../json-model/UBL-TransportationStatusRequest-2.1-Example.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-Waybill-2.3.json ../json-model/UBL-Waybill-2.0-Example-International.json
sh validatejson.sh ../json-schema-model/maindoc/UBL-WeightStatement-2.3.json ../json-model/UBL-WeightStatement-2.2-Example.json
